### ISSUE TITLE
step3 has a problem.what should I do to solve it? change np.int32 to np.float?? 

### ISSUE THREAD

**Issue by cccml** [RiweiChen/FaceTools#14]
Begin Box file Clean and Replace. step(3/6)
Traceback (most recent call last):
  File "main.py", line 131, in <module>
  test(ImagePath,savePathDetect,savePathAligned,savePathCroped,tag_recover=True,savesize=[64,64])
  File "main.py", line 61, in test
    textutil.cleanbox(fileinput=bboxlist,detectlistfile=detectlist,misslistfile=misslist)
  File "C:\Users\cml\Desktop\FaceTools-master\textutil.py", line 129, in cleanbox
    newline=retain_max_face(line)
  File "C:\Users\cml\Desktop\FaceTools-master\textutil.py", line 103, in retain_max_face
    areas=np.empty((num_detect,),dtype=np.int32)#保留的是图像的面积
TypeError: 'float' object cannot be interpreted as an integer

**Comment by yuanyuan29** [comment]
我也遇到了同样的问题，请问题主解决了吗
