### ISSUE TITLE
用来处理LFW人脸库的时候  老是提示下面的错误而终止 求解决~~

### ISSUE THREAD

**Issue by yzk0281** [RiweiChen/FaceTools#3]
Done make file list. step(1/6)
Begin Face Detection task. step(2/6)
Image Number = 1
No.0
Done Face Detection task.step(2/6)
Begin Box file Clean and Replace. step(3/6)
Done Box file Clean and Replace. step(3/6)
Begin Face Point Detection. step(4/6)
Done Face Point Detection. step(4/6)
Begin write Points files. step(5/6)
1
5
Traceback (most recent call last):
  File "main.py", line 145, in <module>
    test(ImagePath,PathDetect,PathAligned,CropedPath,tag_recover=True,savesize=[128,128])
  File "main.py", line 115, in test
    textutil.writePoint2File(replacelist,imagepointlist,points)
  File "D:\cnn\FaceTools-master\FaceTools-master\textutil.py", line 88, in writePoint2File
    fn=fid.readline().split()[0]# image filename
IndexError: list index out of range

**Comment by yekeping** [comment]
请问你解决这个问题了吗

**Comment by yekeping** [comment]
还有代码的贡献者说可以用更好的人脸检测算法
